name: edu_air

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  flutter_animate: ^4.2.0
  flutter_riverpod: ^2.5.1
  google_sign_in: ^6.2.1
  geolocator: ^13.0.1
  device_info_plus: ^11.0.0
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/eduair_logo.png
    - assets/images/google.png
    - assets/images/onboarding_1.png
    - assets/images/onboarding_2.png
    - assets/images/onboarding_3.png
    - assets/images/event_parent_meeting.png
    - assets/images/event_science_fair.png
    - assets/images/home_hero_homework.png
    - assets/images/event_football.png
    - assets/images/home_hero_live.png
    - assets/images/event_staff_meeting.png
    - assets/images/teacher_hero_homework.png
    - assets/images/teacher_hero_new_student.png